### ISSUE TITLE
Alt tabbing breaks legendary tooltips

### ISSUE THREAD

**Issue by Sk1nny18** [IMB11/Flow#66] opened 2024-10-15 11:26 UTC
simple explanation, when legendary tooltips is installed and you have flow, alt tabbing breaks all tooltips and requires restart to fix

**Comment by EnderBoy9217** [comment] 2024-10-16 19:34
This occurs with all tooltips, not just legendary tooltips

**Comment by cobaltlol2** [comment] 2024-10-18 12:08
happens 2 me too, really frusterating

**Comment by IMB11** [comment] 2024-10-24 17:32
Duplicate of #58

**Closed by IMB11** 2024-10-24 17:32 UTC
