### ISSUE TITLE
Game registering mouse in different place

### ISSUE THREAD

**Issue by LordEnder-Kitty** [IMB11/Flow#45] opened 2024-07-28 18:39 UTC
I'm sure I don't need to explain everything wrong here. Also, the screenshot doesn't capture it, but my mouse is just to the left of the glass tooltip. 
![image](https://github.com/user-attachments/assets/79ab91c3-f99e-41da-8e79-d21df91f0da9)

Here's the log from when I took that screenshot 
[latest.log](https://github.com/user-attachments/files/16404872/latest.log)

If it matters at all, my operating system is Linux Mint 21 in case that's related at all.

**Comment by IMB11** [comment] 2024-07-28 19:11
Can you disable your mods 1 by 1 to figure out which is causing this issue with Flow?

**Comment by Matynns** [comment] 2024-07-29 02:40
Hi! I'm having the same issue and did a little testing. Based on the mods I'm using and the ones I can see the author using, I can confirm that the issue is not with Jade, Bedrockify, or REI

**Comment by IMB11** [comment] 2024-07-29 12:06
> Can you disable your mods 1 by 1 to figure out which is causing this issue with Flow?
Still need someone to do this - i've tried to reproduce this using your mods and Im unable to

**Comment by mental9k** [comment] 2024-07-29 12:07
i have the same thing here, apparently my game thinks my mouse is at the bottom right which makes my skin look there unless i move my mouse on the other side of the screen

**Comment by IMB11** [comment] 2024-07-29 12:10
You have an inventory blur mod installed, remove it, Flow has inventory blur built in.

**Comment by MATRIX-feather** [comment] 2024-07-29 15:24
It looks like when Smooth Scrolling is installed, this will happen:

https://github.com/user-attachments/assets/545de853-17c0-4657-ba54-cba44ee9661e

**Comment by IMB11** [comment] 2024-07-29 15:26
Thank you! Will look into it.

**Comment by LordEnder-Kitty** [comment] 2024-07-29 19:47
> You have an inventory blur mod installed, remove it, Flow has inventory blur built in.

I like the look of the other mod better tho. I even modified the last version of this mod to remove all the blur stuff cause it didn't work with it. lol.

**Comment by SmajloSlovakian** [comment] 2024-07-30 08:25
hi, i'm the developer of the mod https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling
from my testing on 1.21 with only your mod and its dependencies, i discovered that there are still some issues like this and my mod only makes the issues worse.

in creative inventory, there seem to be two cursor positions. the cursor in the following screenshots are drawn in because windows' snip&sketch doesn't capture it
![obrázok](https://github.com/user-attachments/assets/ef9c84bd-5554-4859-be5a-a66a619dcf9b)

the player model in the **survival** inventory screen is looking based on wrong cursor position (this is not present in creative inventory)
![obrázok](https://github.com/user-attachments/assets/bbc2a17c-a6a0-4286-b0e3-7a951ff80e00)

there is also a problem with minimizing the game when some kind of inventory screen is open
[crash-2024-07-30_10.15.56-client.txt](https://github.com/user-attachments/files/16424524/crash-2024-07-30_10.15.56-client.txt)

hope this helps you with fixing the issues!

**Comment by IMB11** [comment] 2024-07-30 09:57
Hi @SmajloSlovakian, you'll need to disable your functionality when Flow's RenderHelper class is caching the current screen into a new frame buffer, you could use FabricLoader's shared object storage API to add a smoothscrolling:temporary_disable boolean which I can toggle in Flow when RenderHelper is currently caching the screen.

Alternatively you can add a modImplementation on Flow via Modrinth maven and simply:

```
if FabricLoader.isModLoaded("flow")
    if RenderHelper.isRendering -> skip mouse scroll functionality.
```

**Comment by SmajloSlovakian** [comment] 2024-07-30 10:43
as i said, i'm having related issues with your mod only and without my mod installed. i believe that you have a root cause of the issue which my mod is only making worse but is not causing it... i think it will be better to let you figure out what is happening on your side with only your mod installed and when your issues are fixed and there are still some compatibility issues, i can make some changes in my mod too... the only current problem with my mod is that when i disable creative screen smooth scrolling in the config, it still behaves worse than without my mod but that's a general compatibility issue on my side which i will fix some day

**Comment by IMB11** [comment] 2024-07-30 10:46
I cant add compatability because all of your logic is within mixins - I'd have to perform pretty invasive mixinsquared inject and cancellations into your mixins.

**Comment by IMB11** [comment] 2024-07-30 10:57
Fixed in 2.0.1 - @SmajloSlovakian Flow now stores whether or not it's caching the screen in the `flow:is_caching_screen` boolean

**Comment by SmajloSlovakian** [comment] 2024-07-30 10:58
right now i'm not talking about compatibility but about issues with your mod **without smooth scrolling**
the issues i laid out in my first comment are all without my mod installed and only with the mod flow and its dependencies and i think that they are the ones that should be fixed first

**Closed by IMB11** 2024-07-30 10:57 UTC
Labels: bug, question

**Comment by IMB11** [comment] 2024-07-30 10:58
Yes I know, I have fixed the mouse issue

**Comment by SmajloSlovakian** [comment] 2024-07-30 10:59
oh have you? okay then... i'll test it when i'll be able to and i'll see if there are problems and what i can do with them

**Comment by IMB11** [comment] 2024-07-30 11:00
See https://github.com/IMB11/Flow/commit/7f635cec9c2c471440b160f44b47faf0b6644d3d

**Comment by SmajloSlovakian** [comment] 2024-07-30 11:34
ok... every mouse related issue which was present is now fixed even with my mod installed... now there are just issues with my mod's functionality like moving the items when scrolling which may be fixable by using the fabric's shared objects like you said, i'll try that later... thanks
