### ISSUE TITLE
Background options are not being applied.

### ISSUE THREAD

**Issue by AntonioCrazi** [IMB11/Flow#63] opened 2024-09-17 12:57 UTC
Even checking the "Disable background tint" option, the tint still appears.
When I try to change the tint color, it is not applied. The blur is also not being applied.
Animations are working correctly.

Here's the [log](https://mclo.gs/eujzmxB).

![2024-09-17_09 54 06](https://github.com/user-attachments/assets/09de01da-ef0b-4f79-8817-70dce8515694)
![2024-09-17_09 53 52](https://github.com/user-attachments/assets/19d99f72-febd-4097-924c-b096e4efa3ac)

**Comment by IMB11** [comment] 2024-10-24 17:32
Duplicate of #64

**Closed by IMB11** 2024-10-24 17:32 UTC
