### ISSUE TITLE
Crash When Exiting Crafting Menu and Opening Inventory

### ISSUE THREAD

**Issue by gwenphalan** [IMB11/Flow#65] opened 2024-09-20 02:56 UTC
**Bug Report: Crash When Exiting Crafting Menu and Opening Inventory**

**Mod**: Flow  
**Mod Version**: 1.6.1+1.21  
**Minecraft Version**: 1.21  
**Fabric API Version**: 0.100.7+1.21  

---

### **Description**

The game crashes with a `java.lang.ArithmeticException: / by zero` error when I exit the crafting menu and immediately open my inventory. This crash occurs consistently under these conditions.

---

### **Steps to Reproduce**

1. Launch Minecraft with the Flow mod installed.
2. Open the crafting menu (e.g., by interacting with a crafting table).
3. Exit the crafting menu.
4. Immediately press the key to open the inventory (default is 'E').
5. The game crashes to desktop.

---

### **Expected Behavior**

The game should seamlessly transition from the crafting menu to the inventory without any crashes or errors.

---

### **Observed Behavior**

The game crashes with an `ArithmeticException` error, indicating a division by zero in the Flow mod during HUD rendering.

---

### **Crash Report Excerpt**

```
java.lang.ArithmeticException: / by zero
    at net.minecraft.class_514.method_48579(class_514.java:99)
    at net.minecraft.class_339.method_25394(class_339.java:66)
    at net.minecraft.class_513.method_2634(class_513.java:126)
    at net.minecraft.class_507.method_25394(class_507.java:305)
    at net.minecraft.class_479.method_25394(class_479.java:58)
    at dev.imb11.flow.Flow.lambda$onInitializeClient$2(Flow.java:42)
    at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28)
    at net.minecraft.class_329.handler$dcl000$fabric-rendering-v1$render(class_329.java:9038)
    at net.minecraft.class_329.method_1753(class_329.java:220)
```

---

### **System Information**

- **Operating System**: Windows 11 (64-bit)
- **Java Version**: OpenJDK 21.0.3 (64-bit)
- **CPU**: Intel Core i7-9750H @ 2.60GHz (6 cores, 12 threads)
- **GPU**: NVIDIA GeForce RTX 2060
- **RAM**: 8 GB allocated to Minecraft
- **Mods Loaded**: (Only listing relevant mods)
  - **Flow**: 1.6.1+1.21
  - **Fabric API**: 0.100.7+1.21
  - **Indium**: 1.0.34+mc1.21
  - **Sodium**: 0.5.11+mc1.21
  - **Iris**: 1.7.3+mc1.21

---

### **Reproduction Rate**

- The crash occurs **100% of the time** when following the steps to reproduce.

---

### **Attachments**

- **Full Crash Report**: *[Please find the attached crash report for detailed information.](https://pastebin.com/4bw9JZEx)*

---

### **Notes**

- The issue does not occur if there is a slight delay between exiting the crafting menu and opening the inventory.
- No other mods seem to directly affect this crash, but the interaction between the Flow mod and the HUD rendering system is critical.
- If you need any additional information or testing, please let me know, and I'll be happy to assist.

---

**Thank you for your time and for developing the Flow mod. It's a fantastic addition to the game, and I hope this report helps improve it further.**

**Comment by IMB11** [comment] 2024-10-24 17:32
Duplicate of #58

**Closed by IMB11** 2024-10-24 17:32 UTC
